### PR TITLE
Deduplicate code of Mount and CreateFileSystem

### PR DESCRIPTION
**Pull request by uholzer**
As requested in https://github.com/dokan-dev/dokan-dotnet/pull/284/#issuecomment-1043381198 , here the introduction of the ConfigureInstance method, which deduplicates code from Mount and CreateFileSystem.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @uholzer ,
Thanks for the pull request! Looks like there is a mix of content in the commit. Would you be able to take a look at it ?
Like the `SafeBuffer` for DokanMain and a keepalive removed.

**Comment by uholzer** [comment]
Depends on which stance we want to take:

1. Use DokanInstance and SafeBuffer in both cases, as I have done in this pull request. This means that the class NativeMethods needs to take a SafeBuffer and  that we `GC.KeepAlive` the instance.
2. Not change NativeMethods, i.e. keep passing `DOKAN_OPTIONS` and `DOKAN_OPERATIONS` instead of a SafeBuffer to Mount. Additionally, let ConfigureInstance return a `Tuple<DOKAN_OPTIONS, DOKAN_OPERATIONS>` instead of a DokanInstance. Also, the two GC.KeepAlive we have now, remain as they are.

Given your feedback, I assume you like option 2 better. This makes sense in my opinion as it does not change how we invoke DokanMain. I will update the pull request accordingly.

**Comment by LTRData** [comment]
I agree on # 2 as well. It makes native calls unnecessarily complicated to introduce SafeBuffer etc in calls that actually do not need them. I also assume that the entire GC.KeepAlive thing will be unnecessary at some point in the future and that makes it even more unnecessary to manually marshal objects for this particular native call. GC.KeepAlive has never been needed before and it looks like it is only needed in some very specific scenarios right now most probably due to some framework bug.

**Comment by uholzer** [comment]
Option 2 is ready. I made two functions, one for the options and one for the operations. (I gave up on a single function returning a tuple because destructuring is not possible before .NETFramework 4.7 and doing it manually looks ugly.)

**Comment by Liryna** [comment]
Thank you very much @uholzer for the quick change! 🏆

**Pull request merged**
