### PR TITLE
moved .net46 to .net 461 and added .net6.0-window in the TFM

### PR DESCRIPTION
**Pull request by TrabacchinLuigi**
added .net6 compatibility, upped .net4.6 to 4.6.1, and removed the need to sign the test assembly

### CODE REVIEW

**Comment by Liryna** [comment]
Thanks for the pull request! Looks like there is an issue with the CI  😢 but it does have 4.6.1 https://www.appveyor.com/docs/windows-images-software/
https://ci.appveyor.com/project/Liryna/dokan-dotnet/builds/42829412/job/rijcjmdmx09eff04

**Comment by TrabacchinLuigi** [comment]
it looked like .net 6 was missing, but, it's really not my area of expertise

**Comment by Liryna** [comment]
True! Well found. @TrabacchinLuigi Can you update the appveyor file at the root in your pull request to change 2019 to 2022?

**Comment by Liryna** [comment]
Garbage collector is behaving differently on release. It has proven to be very helpful to have both run.

Looks like it is building but none are succeeding :(

**Comment by TrabacchinLuigi** [comment]
And how is garbage collection tested ? :raised_eyebrow:
Nevermind i'll revert that part

**Comment by Liryna** [comment]
For example when we moved to V2 we had the GC releasing the native memory only on release https://github.com/dokan-dev/dokan-dotnet/issues/280

**Pull request closed without merging**
