### PR TITLE
Mirror parameters

### PR DESCRIPTION
**Pull request by TrabacchinLuigi**
Added some convenient parameters to run mirror in different folders

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

Thank you for your contribution as always !
This mirror options are well welcomed ! Could you just change the typo imput to input ?

Also it seems like the test CI does not pass 😢 
https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.1.0-396/job/wkiewemxkjerrfs4#L293

**Comment by TrabacchinLuigi** [comment]
Hey!
Uhm i didn't even mean to try  to push that commit, wanted to push only the parameters because seemed comfy…
Btw that fixed some files being hanged open in our implementation, maybe setting it to an object instead of null is more the way to go in this implementation, let me see

**Comment by TrabacchinLuigi** [comment]
Ohhh ok i got it... since it was hardcoded that it was mounting C:\ in N:\ the test are not running because it's expecting it to be like that, we need to pass the new parameters for it to work, where can i edit that ?

**Comment by Liryna** [comment]
Humm probably should set the previous value as default if nothing is given in parameters. 
Otherwise `info.Context = null` would be the correct way here. object is only used to flag that it is a folder.

**Comment by TrabacchinLuigi** [comment]
> Humm probably should set the previous value as default if nothing is given in parameters
Gonna lose all the nice interactivity where if no parameters are given user is asked, also someone could want to run tests in different locations, so making the parameters explicit would be easier to understand for them how to change them
> Otherwise info.Context = null would be the correct way here. object is only used to flag that it is a folder.
strange the commit where i give an object is passing AppVeyor again ...

**Pull request closed without merging**
