### PR TITLE
IDokanFileInfo is now the parameter for IDokanOperations(Unsafe)?.

### PR DESCRIPTION
**Pull request by kyanha**
**THIS IS A BREAKING CHANGE.**

All implementations of `IDokanOperations` will need to change their final
parameters to accept `IDokanFileInfo` instead of bare `DokanFileInfo`.

New class: `MockDokanFileInfo` This is accepted by implementations of
`IDokanOperations` and `IDokanOperationsUnsafe` as their final
parameters.  You can set all of the values of the public
interfaces of `IDokanFileInfo` (which itself was extracted from the
publicly accessible fields of `DokanFileInfo`), and specify the
mock behavior of both `.TryResetTimeout()` and `.GetRequestor()`.

To use this, your unit test mock code needs to behave as though it is
Dokan, calling into your `IDokanOperations` implementation with
various parameters and testing the expected behaviors and return
values.  Integration tests with Dokan still need to use something
like `DokanNet.Tests`.

### CODE REVIEW

**Comment by kyanha** [comment]
Associated with #183.  Appveyor actually ran on this one, after commit 9f0933a.

**Comment by Liryna** [comment]
Thank you @kyanha for the PR ! very appreciated and I am sure some people will be glad to finally using unittest 👍

**Comment by Liryna** [comment]
Ah I tought I would be able to squash all the commit but looking at the history you also have the commit from https://github.com/dokan-dev/dokan-dotnet/pull/238 Can you recreate the PR with only the IDokanFileInfo changes ?

**Comment by kyanha** [comment]
I put the target moniker changes in #243, so I'll redo this PR without them.

**Comment by kyanha** [comment]
Superseded by #244

**Pull request closed without merging**
