### PR TITLE
Fixed unit tests for dokany 1.0.0-RC4

### PR DESCRIPTION
**Pull request by viciousviper**
Adapted unit tests in DokanNet.Tests to behavioural changes in dokany 1.0.0-RC4

### CODE REVIEW

**Comment by viciousviper** [comment]
Hi @Liryna,

I've finally gotten around to fixing the DokanNet.Tests suite for dokany 1.0.0-RC4. They are now back to a perfect record in both my local test execution and AppVeyor build.

I have not squashed the individual commits yet - maybe you could to that while merging the PR. A single comment along the lines of the PR title should suffice IMHO. 

When I say "perfect record" I mean the previously existing .NET 4.0-based version of DokanNet. I tried referencing the .NET 4.6-based version from my test suite and all hell broke loose.
One problem seems to be a change in sync/async file mode handling.
Has the 4.6 variant been tested at all?

**Comment by Liryna** [comment]
Hi @viciousviper !

Thank you for the fixies :heart:  ! I will try to merge the missing changes from your PR into the master in a single commit as you said.

About .NET 4.6, I didn't test to say the truth :smile: I was thinking it would change nothing but I am going to test it now !

**Comment by magol** [comment]
@viciousviper Strange that it not working for the .NET 4.6 version.
I have successfully run all unit tests (before this PR), and test with both DokanNetMirror and RegistryFS.
What is the problems you see?

**Comment by viciousviper** [comment]
@magol haven't had time so far to dig deeper into matters. I just very briefly changed the assembly ref to the .NET 4.6 variant and got about 10 errors in FileInfoTests citing something like an invalid stream operation due to the async state of the file handle.

**Comment by magol** [comment]
I have try to run the tests from the PR on my machine, and I get the same result both for .NET 4.0 and .NET 4.6

But to be able to run the tests, I have to use `MockBehavior.Loose` instead of `MockBehavior.Strict`
And I still get 10 failed tests. 

- CopyTo_WhereSourceIsEmpty_CallsApiCorrectly
> FileInfoTests.cs : line 251
> Test Outcome:	Failed
> Test Duration:	0:00:00,0417389
> 
> Result StackTrace:	
> at Moq.Mock.Verify()
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1397
>    at DokanNet.Tests.FileInfoTests.CopyTo_WhereSourceIsEmpty_CallsApiCorrectly() in FileInfoTests.cs:line 275
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.CopyTo_WhereSourceIsEmpty_CallsApiCorrectly threw exception: 
> Moq.MockVerificationException: The following setups were not matched:
> IDokanOperations d => d.CreateFile("\DestinationFile.txe", FileAccess.ReadData, WriteData, AppendData, ReadExtendedAttributes, WriteExtendedAttributes, ReadAttributes, WriteAttributes, Delete, ReadPermissions, ChangePermissions, Synchronize, FileShare.None, FileMode.CreateNew, FileOptions.SequentialScan, FileAttributes.Normal, It.Is<DokanFileInfo>(i => i.IsDirectory == False))
> IDokanOperations d => d.CloseFile("\DestinationFile.txe", It.Is<DokanFileInfo>(i => (i.Context == null && i.IsDirectory == False) && i.DeleteOnClose == False))

- CopyTo_WhereSourceIsLargeFile_CallsApiCorrectly
> Test Source:	FileInfoTests.cs : line 323
> Test Outcome:	Failed
> Test Duration:	0:00:00,4455842
> 
> Result StackTrace:	
> at lambda_method(Closure )
>  --- End of inner exception stack trace ---
>     at Moq.Mock.Verify()
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1397
>    at DokanNet.Tests.FileInfoTests.CopyTo_WhereSourceIsLargeFile_CallsApiCorrectly() in FileInfoTests.cs:line 358
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.CopyTo_WhereSourceIsLargeFile_CallsApiCorrectly threw exception: 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

- CopyTo_WhereSourceIsNonEmpty_CallsApiCorrectly
> Test Source:	FileInfoTests.cs : line 282
> Test Outcome:	Failed
> Test Duration:	0:00:00,0375617
> 
> Result StackTrace:	
> at Moq.Mock.Verify()
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1397
>    at DokanNet.Tests.FileInfoTests.CopyTo_WhereSourceIsNonEmpty_CallsApiCorrectly() in FileInfoTests.cs:line 317
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.CopyTo_WhereSourceIsNonEmpty_CallsApiCorrectly threw exception: 
> Moq.MockVerificationException: The following setups were not matched:
> IDokanOperations d => d.CreateFile("\DestinationFile.txe", FileAccess.ReadData, WriteData, AppendData, ReadExtendedAttributes, WriteExtendedAttributes, ReadAttributes, WriteAttributes, Delete, ReadPermissions, ChangePermissions, Synchronize, FileShare.None, FileMode.CreateNew, FileOptions.SequentialScan, FileAttributes.Normal, It.Is<DokanFileInfo>(i => i.IsDirectory == False))

- GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly
> Test Source:	DirectoryInfoTest.cs : line 925
> Test Outcome:	Failed
> Test Duration:	0:00:00,1610379
> 
> Result1 Name:	GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly (Data Row 0)
> Result1 Outcome:	Failed
> Result1 Duration:	0:00:00,0931301
> Result1 StackTrace:	
> at DokanNet.Tests.DokanOperationsFixture.PrepareVerify() in DokanOperationsFixture.cs:line 1381
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1395
>    at DokanNet.Tests.DirectoryInfoTest.GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly() in DirectoryInfoTest.cs:line 967
> Result1 Message:	
> Test method DokanNet.Tests.DirectoryInfoTest.GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly threw exception: 
> System.InvalidOperationException: Negative pending files count
> 
> Result2 Name:	GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly (Data Row 1)
> Result2 Outcome:	Failed
> Result2 Duration:	0:00:00,0679078
> Result2 StackTrace:	
> at DokanNet.Tests.DokanOperationsFixture.PrepareVerify() in DokanOperationsFixture.cs:line 1381
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1395
>    at DokanNet.Tests.DirectoryInfoTest.GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly() in DirectoryInfoTest.cs:line 967
> Result2 Message:	
> Test method DokanNet.Tests.DirectoryInfoTest.GetFileSystemInfos_OnRootDirectory_WhereSearchOptionIsAllDirectories_CallsApiCorrectly threw exception: 
> System.InvalidOperationException: Negative pending files count

- MoveTo_WhereParentIsDirectory_CallsApiCorrectly
> Test Source:	DirectoryInfoTest.cs : line 1003
> Test Outcome:	Failed
> Test Duration:	0:00:00,0424665
> 
> Result StackTrace:	
> at DokanNet.Tests.DokanOperationsFixture.PrepareVerify() in DokanOperationsFixture.cs:line 1386
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1395
>    at DokanNet.Tests.DirectoryInfoTest.MoveTo_WhereParentIsDirectory_CallsApiCorrectly() in DirectoryInfoTest.cs:line 1027
> Result Message:	
> Test method DokanNet.Tests.DirectoryInfoTest.MoveTo_WhereParentIsDirectory_CallsApiCorrectly threw exception: 
> System.TimeoutException: Cleanup wait cycles exceeded

- MoveTo_WhereParentIsDirectory_CallsApiCorrectly
> Test Source:	FileInfoTests.cs : line 564
> Test Outcome:	Failed
> Test Duration:	0:00:00,037551
> 
> Result StackTrace:	
> at Moq.Mock.Verify()
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1397
>    at DokanNet.Tests.FileInfoTests.MoveTo_WhereParentIsDirectory_CallsApiCorrectly() in FileInfoTests.cs:line 589
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.MoveTo_WhereParentIsDirectory_CallsApiCorrectly threw exception: 
> Moq.MockVerificationException: The following setups were not matched:
> IDokanOperations d => d.CreateFile("\DestinationDir\DestinationFile.txe", FileAccess.WriteData, Synchronize, FileShare.ReadWrite, FileMode.Open, FileOptions.None, FileAttributes.0, It.Is<DokanFileInfo>(i => i.IsDirectory == False))

- MoveTo_WhereParentIsRoot_CallsApiCorrectly
> Test Source:	DirectoryInfoTest.cs : line 974
> Test Outcome:	Failed
> Test Duration:	0:00:00,0463552
> 
> Result StackTrace:	
> at Moq.Mock.Verify()
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1397
>    at DokanNet.Tests.DirectoryInfoTest.MoveTo_WhereParentIsRoot_CallsApiCorrectly() in DirectoryInfoTest.cs:line 996
> Result Message:	
> Test method DokanNet.Tests.DirectoryInfoTest.MoveTo_WhereParentIsRoot_CallsApiCorrectly threw exception: 
> Moq.MockVerificationException: The following setups were not matched:
> IDokanOperations d => d.CreateFile("\DestinationDir", FileAccess.AppendData, Synchronize, FileShare.ReadWrite, FileMode.Open, FileOptions.None, FileAttributes.0, It.Is<DokanFileInfo>(i => i.IsDirectory == False))
> IDokanOperations d => d.CreateFile("\", FileAccess.AppendData, Synchronize, FileShare.ReadWrite, FileMode.Open, FileOptions.None, FileAttributes.0, It.Is<DokanFileInfo>(i => i.IsDirectory))

- MoveTo_WhereParentIsRoot_CallsApiCorrectly
> Test Source:	FileInfoTests.cs : line 534
> Test Outcome:	Failed
> Test Duration:	0:00:00,0405704
> 
> Result StackTrace:	
> at Moq.Mock.Verify()
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1397
>    at DokanNet.Tests.FileInfoTests.MoveTo_WhereParentIsRoot_CallsApiCorrectly() in FileInfoTests.cs:line 557
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.MoveTo_WhereParentIsRoot_CallsApiCorrectly threw exception: 
> Moq.MockVerificationException: The following setups were not matched:
> IDokanOperations d => d.CreateFile("\DestinationFile.txe", FileAccess.WriteData, Synchronize, FileShare.ReadWrite, FileMode.Open, FileOptions.None, FileAttributes.0, It.Is<DokanFileInfo>(i => i.IsDirectory == False))
> IDokanOperations d => d.CreateFile("\", FileAccess.WriteData, Synchronize, FileShare.ReadWrite, FileMode.Open, FileOptions.None, FileAttributes.0, It.Is<DokanFileInfo>(i => i.IsDirectory))

- Replace_WhereParentIsDirectory_CallsApiCorrectly
> Test Source:	FileInfoTests.cs : line 1522
> Test Outcome:	Failed
> Test Duration:	0:00:00,0813051
> 
> Result StackTrace:	
> at DokanNet.Tests.DokanOperationsFixture.PrepareVerify() in DokanOperationsFixture.cs:line 1381
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1395
>    at DokanNet.Tests.FileInfoTests.Replace_WhereParentIsDirectory_CallsApiCorrectly() in FileInfoTests.cs:line 1558
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.Replace_WhereParentIsDirectory_CallsApiCorrectly threw exception: 
> System.InvalidOperationException: Negative pending files count

- Replace_WhereParentIsRoot_CallsApiCorrectly
> Test Source:	FileInfoTests.cs : line 1482
> Test Outcome:	Failed
> Test Duration:	0:00:00,0785214
> 
> Result StackTrace:	
> at DokanNet.Tests.DokanOperationsFixture.PrepareVerify() in DokanOperationsFixture.cs:line 1381
>    at DokanNet.Tests.DokanOperationsFixture.Verify() in DokanOperationsFixture.cs:line 1395
>    at DokanNet.Tests.FileInfoTests.Replace_WhereParentIsRoot_CallsApiCorrectly() in FileInfoTests.cs:line 1515
> Result Message:	
> Test method DokanNet.Tests.FileInfoTests.Replace_WhereParentIsRoot_CallsApiCorrectly threw exception: 
> System.InvalidOperationException: Negative pending files count

**Comment by viciousviper** [comment]
@magol This hints at a deeper problem in your machine configuration - the behaviour of the underlying dokany driver does not match with the expectations of the test suite.
Disabling `MockBehavior.Strict` kinda defeats the purpose of the test suite - namely to capture each and every API call and to detect any missing, surplus, or differently parameterized API calls.

Seeing how the latest AppVeyour tests ran fine I'd first ask you to check precisely which version of dokany you are using. There have been significant changes between 1.0.0-RC3 and 1.0.0-RC4 where the exact sequence of calls is concerned.

**Comment by viciousviper** [comment]
@magol Another possibility would be that your test configuration is set to use x86 instead of x64 - please check under VS2015 menu Test/Test configuration/Default processor architecture.

**Comment by magol** [comment]
Ahhh! I did have RC3 installed, so I have now updated to RC4.
I have also set the Default processor architecture to x64 and reset to `MockBehavior.Strict`

But, it do not fix my problems. I now have 54 failed tests when I test the .NET 4.0 version :-(

**Comment by viciousviper** [comment]
@magol Using the `NETWORK_DRIVE` setting or not?

**Comment by magol** [comment]
@viciousviper  No, I do not use `NETWORK_DRIVE`

**Comment by Liryna** [comment]
@viciousviper I have try to merge the changes but I got totally lost in what should be changed and what should not :disappointed: do you think you can move your changes to a clean history ? :heart: 

About 4.6 test, I tried to move the mirror to 4.6 and reference the dokannet4.6 but I cannot build:
```
1>C:\Project\dokan-dotnet\sample\DokanNetMirror\Mirror.cs(50,26,50,37): error CS0012: The type 'FormattableString' is defined in an assembly that is not referenced. You must add a reference to assembly 'StringInterpolationBridge, Version=0.9.1.0, Culture=neutral, PublicKeyToken=761dcf67ba0bf74d'.
1>C:\Project\dokan-dotnet\sample\DokanNetMirror\Mirror.cs(62,17,62,28): error CS0012: The type 'FormattableString' is defined in an assembly that is not referenced. You must add a reference to assembly 'StringInterpolationBridge, Version=0.9.1.0, Culture=neutral, PublicKeyToken=761dcf67ba0bf74d'.
1>C:\Project\dokan-dotnet\sample\DokanNetMirror\Mirror.cs(234,35,234,46): error CS0012: The type 'FormattableString' is defined in an assembly that is not referenced. You must add a reference to assembly 'StringInterpolationBridge, Version=0.9.1.0, Culture=neutral, PublicKeyToken=761dcf67ba0bf74d'.
1>C:\Project\dokan-dotnet\sample\DokanNetMirror\Mirror.cs(258,35,258,46): error CS0012: The type 'FormattableString' is defined in an assembly that is not referenced. You must add a reference to assembly 'StringInterpolationBridge, Version=0.9.1.0, Culture=neutral, PublicKeyToken=761dcf67ba0bf74d'.
```

That's strange :cry:

**Comment by magol** [comment]
@Liryna I got that errors to before I removed [`packages.config`](https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/packages.config) in DokanNetMirror. In `packages.config` it is a reference to "`StringInterpolationBridgeStrong`" that contains `FormattableString`. But `FormattableString `already exists in .NET 4.6, and it become a conflict. 

So simply remove `packages.config`, and the project should compile and run as expected (it works for me)

**Comment by Liryna** [comment]
@magol :+1: it worked, I also had to directly target the dokannet dll and not the project 4.6.

**Comment by magol** [comment]
@Liryna Grate that it works :-)
But, strange that you cannot reference to the 4.6 project. I do reference to the project, and it works for me.


Something to consider if we maybe also should have double sets of `DokanNetMirror` and `DokanNet.Tests`, one for .NET 4.0 and .NET 4.6. It might be a value to run the tests against both environments, even if it is exactly the same code

The downside is that everything becomes more complicated, and it takes longer to run the tests. But it is foolish not to have tests for everything.

**Pull request closed without merging**
