### PR TITLE
Fixed unit tests

### PR DESCRIPTION
**Pull request by viciousviper**
Enabled disambiguation of Dokan API calls between different unit test methods
Allowed out of process calls to Cleanup in Overlapped tests

This PR replaces PR #63

### CODE REVIEW

**Comment by viciousviper** [comment]
Missed two commits while squashing :-(.
Is this ok or do you insist on getting the PR in a single commit?

**Comment by viciousviper** [comment]
BTW Liryna - do you have any experience in configuring coverity for .NET projects?
I've spent most of this afternoon trying to get the blasted thing to work but it still doesn't emit anything from cov-build. :-[
And the coverity community is conveniently offline for maintenance :-(

**Comment by Liryna** [comment]
Thank you @viciousviper for the rebase :smiley: !

About cov, this build https://ci.appveyor.com/project/viciousviper/cloudfs/build/job/niamnpo6vnxnk9uw seems to have work no ?
What is your issue ?
(I never used with C# but tu output seems to be alright)

**Comment by viciousviper** [comment]
Well, the devil is in the details.
The build itself works allright, but coverity is still unable to pick up any analysis data:
> [WARNING] No files were emitted. This may be due to a problem with your configuration 
> or because no files were actually compiled by your build command.
> Please make sure you have configured the compilers actually used in the compilation.
>  For more details, please look at: 
>     C:/projects/cloudfs/cov-int/build-log.txt

I'll mail coverity support - maybe they can shed some light on this matter.

**Pull request merged**
