### PR TITLE
Clean up and document DokanError.

### PR DESCRIPTION
**Pull request by nitroxis**
Cleaned up the DokanError enumeration by removing the redundant and wrong "Error" word in front of each value (e.g. ErrorError, ErrorSuccess). Also documented the errors using the Windows API header.

### CODE REVIEW

**Comment by Liryna** [comment]
Ah thats much better I agree :smiley:  !
Could you also fix the samples ?

**Comment by nitroxis** [comment]
Oh yes, I forgot. I'll fix them.

**Comment by nitroxis** [comment]
Ugh. The samples don't work because the project files and references are messed up. Mind if I fix this by creating one solution that contains the sample projects and reference the DokanNet library as project, and not the DLL itself?

**Comment by Liryna** [comment]
ohhh, ok !

**Comment by nitroxis** [comment]
"DokanError" should probably also be renamed to "DokanResult", because not all of the values are actual errors, such as "Success".

**Comment by nitroxis** [comment]
Okay, I fixed the samples.

**Comment by Liryna** [comment]
I agree that "DokanError" should be renamed to "DokanResult".
Sorry to ask you again but could you do it :D ?

**Comment by nitroxis** [comment]
Sure.

**Comment by nitroxis** [comment]
There you go.

**Comment by Liryna** [comment]
Perfect, Thank you !

**Pull request merged**
