### PR TITLE
Fix unit tests in dokan-dotnet for dokany 1.0.0-RC1 through 1.0.0-RC4

### PR DESCRIPTION
**Pull request by viciousviper**
Updates for 1.0.0-RC3 - unsquashed

### CODE REVIEW

**Comment by Liryna** [comment]
@viciousviper I have currently disabled test units because there is an issue with MoveTo tests. it seems like there is new CreateFile that is now proceed that make the test fail.
I have been able to make it work :cry: 

https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.0.0-221/job/k10pqpd8djecus9f

**Comment by viciousviper** [comment]
Ok, I'll look into the test suite in the next couple of days.
Had to reinstall my dev rig again due to problems with Visual Studio 2015 Update 3. Better keep your hands off of that version - it destroys the integrated Test Explorer window and C# code analysis. :angry:

**Comment by viciousviper** [comment]
Please try commit #2790de2.
All the MoveTo(...) and the FileInfo.Replace(...) tests should work again on dokany 1.0.0-RC4.

**Comment by Liryna** [comment]
Thank you @viciousviper very appreciate !
This solved perfectly the appveyor behaviour :+1: 

The pull request history was unclean so I created a patch of your contribution and adding it to the master.
https://github.com/dokan-dev/dokan-dotnet/commit/71dbc10fd6a54835170aa4cf989f66a78060a2ae
https://github.com/dokan-dev/dokan-dotnet/commit/def1ebfb6013c19c68eb639994f472e860ffe2dd

**Comment by Liryna** [comment]
@viciousviper sorry to bother you again :cry: 
There is a test where it can happen that it fail
https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.0.0-248/job/yvgcx4b3kamts03k

Could you explain me how you find what is making him fail on appveyor by the output ?

**Comment by viciousviper** [comment]
Hi Liryna,
no worries - I don't feel bothered. 😉  

Looking at the AppVeyor log it appears at first sight that in test *Open_WhereFileModeIsAppend_CallsApiCorrectly* there is an extra call to `CloseFile("\File.ext", ...)` where none is expected - or possibly the call to `CloseFile("\File.ext",...)` has a set of parameters different to what is expected.

This is in essence what 
> CloseFile (DokanFileInfo {<null>, , , , , 2436, , }) -> **MockException**: IDokanOperations.CloseFile("\File.ext", {<null>, False, False, False, False, #2436, False, False}) invocation failed with mock behavior Strict.
> All invocations on the mock must have a corresponding setup.

means.

On closer inspection I don't find anything wrong with the AppVeyor test log - the log of a local test execution on my machine produces the exact same call to `CloseFile("\File.ext", ...)`.

My current suspicion, therefore, is something different. It could be possible that invocation of `CloseFile(...)` is bleeding over from one of the other tests, most likely the previous test *MoveTo_WhereTargetExists_Throws* but was mistakenly counted towards *Open_WhereFileModeIsAppend_CallsApiCorrectly*. I seem to recall that this used to happen at some point in time.

What I'd do next is activate the **SPECIFIC_NAMES** compile flag on the DokanNet.Tests project which will result in the different tests using individual test file names instead of all sharing "File.ext". This will allow you to see if the failure actually originates from *Open_WhereFileModeIsAppend_CallsApiCorrectly* or if there is some strange kind of crosstalk.

BTW - is this error persistent or do you only see it every now and then?

**Comment by viciousviper** [comment]
For that to actually work you'll need to fix a bug that has crept in because I haven't needed this kludge for a while - sorry for that:

Change the code following line 620 to look like:

>  #if !SPECIFIC_NAMES
>          private string Named(string name) => name;
>  #else
>          private string Named(string name) => $"{currentTestName}_{name}";
>  #endif
> 
>         private FileInformation[] Named(FileInformation[] infos)
>             => infos.Aggregate(new List<FileInformation>(), (l, i) => { l.Add(Named(i)); return l; }, l => l.ToArray());
> 
>         private FileInformation Named(FileInformation info) => new FileInformation()
>         {
>             FileName = Named(info.FileName), Attributes = info.Attributes,
>             CreationTime = info.CreationTime, LastAccessTime = info.LastAccessTime, LastWriteTime = info.LastWriteTime,
>             Length = info.Length
>         };

i.e. remove the `static` qualifiers.

**Comment by viciousviper** [comment]
On my local machine this now produces the following log for the test in question:

> Testname:	Open_WhereFileModeIsAppend_CallsApiCorrectly
> Testergebnis:	Erfolgreiche
> Ergebnis StandardOutput:	
> Open Append/Write
> CreateFile\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", [WriteData, AppendData, > WriteExtendedAttributes, ReadAttributes, WriteAttributes, ReadPermissions, Synchronize], [None], OpenOrCreate, [None], [0], DokanFileInfo {<null>, , , , , 8632, , })
> GetFileInformation\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", out [FileInformation {\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 8632, , })
> GetFileInformation\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", out [FileInformation {\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 8632, , })
> GetFileInformation\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", out [FileInformation {\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 8632, , })
> GetFileInformation\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", out [FileInformation {\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 8632, , })
> GetFileInformation\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", out [FileInformation {\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 8632, , })
> WriteFile[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", [4096], out 4096, 0, DokanFileInfo {<null>, , , , , 8632, SynchronousIo, })
> GetFileInformation\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", out [FileInformation {\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 8632, , })
> Cleanup\[1] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", DokanFileInfo {<null>, , , , , 8632, , })
> Waiting for closure (\#1)
> CloseFile\[0] ("\Open_WhereFileModeIsAppend_CallsApiCorrectly_File.ext", DokanFileInfo {<null>, , , , , 8632, , })

Thus, any single API call and any failure can now be precisely associated to a specific test.

**Comment by viciousviper** [comment]
Just updated my fork from #8bf4413, rebuilt it through AppVeyor, and got **this**:

> Failed   Open_WhereFileModeIsAppend_CallsApiCorrectly
> Error Message:
>    Assert.IsFalse failed. Found Mock invocations without corresponding setups
> Stack Trace:
>    at DokanNet.Tests.FileInfoTests.Cleanup() in C:\projects\dokan-dotnet\DokanNet.Tests\FileInfoTests.cs:line 54
> Standard Output Messages:
>    CloseFile (DokanFileInfo {<null>, , , , , 1828, , }) -> **NullReferenceException**: Object reference not set to an instance of an object.
>    CloseFile (DokanFileInfo {<null>, , IsDirectory, , , 1828, , }) -> **MockException**: > IDokanOperations.CloseFile("\", {<null>, False, True, False, False, #1828, False, False}) invocation failed with mock behavior Strict.
> All invocations on the mock must have a corresponding setup.
>    Open Append/Write
>    CreateFile\[1] ("\File.ext", [WriteData, AppendData, WriteExtendedAttributes, ReadAttributes, WriteAttributes, ReadPermissions, Synchronize], [None], OpenOrCreate, [None], [0], DokanFileInfo {<null>, , , , , 1828, , })
>    GetFileInformation[1] ("\File.ext", out [FileInformation {\File.ext, [Normal], <null>, <null>, <null>, 0}], DokanFileInfo {<null>, , , , , 1828, , })
>    WriteFile\[1] ("\File.ext", [4096], out 4096, 0, DokanFileInfo {<null>, , , , , 1828, SynchronousIo, })
>    Cleanup\[1] ("\File.ext", DokanFileInfo {<null>, , , , , 1828, , })
>    Waiting for closure (#1)
>    CloseFile\[0] ("\File.ext", DokanFileInfo {<null>, , , , , 1828, , })

**Comment by viciousviper** [comment]
And, after activatinc **SPECIFIC_NAMES** this turns into the following log - for the **Debug** configuration only - that proves my point concerning crosstalk.

> Failed   Create_CallsApiCorrectly
> Error Message:
>    Assert.IsFalse failed. Found Mock invocations without corresponding setups
> Stack Trace:
>    at DokanNet.Tests.FileInfoTests.Cleanup() in C:\projects\dokan-dotnet\DokanNet.Tests\FileInfoTests.cs:line 54
> Standard Output Messages:
>    CreateFile\[1] ("\Create_CallsApiCorrectly_File.ext", [ReadData, WriteData, AppendData, ReadExtendedAttributes, WriteExtendedAttributes, ReadAttributes, WriteAttributes, ReadPermissions, Synchronize], [None], Create, [None], [0], DokanFileInfo {<null>, , , , , 1556, , })
>    CloseFile (DokanFileInfo {<null>, , , , , 1556, , }) -> **MockException**: IDokanOperations.CloseFile(**"\CopyTo_WhereTargetExists_Throws_File.ext"**, {<null>, False, False, False, False, #1556, False, False}) invocation failed with mock behavior Strict.
> All invocations on the mock must have a corresponding setup.
>    WriteFile\[1] ("\Create_CallsApiCorrectly_File.ext", [43], out 43, 0, DokanFileInfo {<null>, , , , , 1556, SynchronousIo, })
>    Cleanup\[1] ("\Create_CallsApiCorrectly_File.ext", DokanFileInfo {<null>, , , , , 1556, , })
>    Waiting for closure (#1)
>    CloseFile\[0] ("\Create_CallsApiCorrectly_File.ext", DokanFileInfo {<null>, , , , , 1556, , })

The actual culprit, however, seems to be the test **"\CopyTo_WhereTargetExists_Throws_File.ext"**.
*Could it be possible that dokany formerly just aborted the copy file call sequence when an existing target file was signaled, but executes a final `CloseFile(...)` now?*

**Comment by Liryna** [comment]
The test seems to fail randomly only on appveyor Debug build. So yes it can be a cross call that happen as you explain.

> The actual culprit, therefore, seems to be the test CopyTo_WhereTargetExists_Throws.
Could it be possible that dokany formerly just aborted the copy file call sequence when an existing target file was signaled, but executes a final CloseFile(...) now?

I have to say that I have no idea on it.
Does the `CloseFile("\CopyTo_WhereTargetExists_Throws_File.ext"` happen when running alone ?
For me if the copy fail, it should close the file at the end anyway.

**Comment by viciousviper** [comment]
@Liryna,
please integrate c2724e3, 007b436, and 4bfe0f1.
There were three tests that were missing a `CloseFile()` Mock setup. Either dokany changed its behaviour for cases where a copy or move operation fails due to a preexisting target, or the tests have been silently failing for some time before the latest dokany version.

**Comment by Liryna** [comment]
Hi @viciousviper 

I merged the changes https://github.com/dokan-dev/dokan-dotnet/commit/0bd34386a55854bbbd7903a3513cd0e3dc122ae4
but it seems that some another test is failing https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.0.0-256/job/ei65y8vyca9b86e3

**Pull request closed without merging**
