### PR TITLE
Avoid console logger to switch color and never go back

### PR DESCRIPTION
**Pull request by TrabacchinLuigi**
Avoid console logger to switch color and never go back to the original due to multi threading

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

Well found ! Thank you even more for the PR 👍

**Comment by Liryna** [comment]
Humm, just a thought, could be not just change the color at the logger init and change it back during the dispose ? This would speedup and probably give a better result.

**Comment by TrabacchinLuigi** [comment]
the only way to speed this up i've found is to make ProducerConsumer pattern with many threads filling the print queue and a single consumer printing the messages, but it felt overcomplicated for just an example, i can share that implementation if you want, the color have to be saved and restored every time, but like that prucers won't have to wait for the actual print to happen

**Comment by Liryna** [comment]
Just save the color console at logger init and restore during dispose could not just be enough ?

**Comment by TrabacchinLuigi** [comment]
i don't think you createa new instance of the logger every call.. so no, it won't work

**Comment by Liryna** [comment]
What do you mean by creating at every call ?
Logger instance is a Mount param, there is only one during all the process.

**Comment by TrabacchinLuigi** [comment]
Exactly there is only one instance of the logger, so if you don't reset the console color every time, whatever would call `Console.Writeline()` would write in the last used color, and this is not desirable ...

**Comment by Liryna** [comment]
Our color change is already not atomic, the not desirable behavior can already happen between each reset.
We can probably ensure that the console is ours during the process time.

**Comment by TrabacchinLuigi** [comment]
In fact someone could still call `Console.ForegroundColor = something;` making everything vain... so i see what you mean... we could try ... but i don't think this would really speed up much, the big difference is the lock in my opinion

**Comment by Liryna** [comment]
`_colorLock` would not longer exist at this moment.

**Comment by TrabacchinLuigi** [comment]
nope, if you remove `_colorLock` you could end up writing with wrong colors... 
Two threads could enter simultaneously both set the color they want (let's say gray and red) and then both write in red

**Pull request merged**
