### PR TITLE
Improve comments and fixing spelling.

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by Liryna** [comment]
:+1: Amazing @magol  !!!

There seems to be some warnings about cref
` warning: Missing 'cref' attribute from <seealso> tag.`
https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.0.0-237/job/kuglown2vl96kufc#L518

Can you also merge all your commit into one ?

**Comment by magol** [comment]
aaaa, Doxygen do not understand <see langword="true" />, <see langword="false" /> and <see langword="null" />
I have to use alternative syntax then.

I will try to merge everything to one commit.
I am a GIT newbie, so I guess I do it mostly wrong. Please feel free to help me make it right.
I have to find out how I merge it to a commit. Maybe you can give me a hint where I can read about it? :-)

**Comment by Liryna** [comment]
```
git reset --soft HEAD~3
git commit
```
3 is the number of commit to merge.

Tell me if you have issue with it, I will create a patch for you.

(do a backup before doing it :smiley: )

**Comment by Liryna** [comment]
@magol be careful with jetbrains. It seems to have broken something on your before last commit.

**Comment by magol** [comment]
@Liryna I honestly do not know why it is trying to "help me". Or even which plugin that makes it :-(
Very frustrating to constantly recover what it sets out with. Must try to get rid of this, but have not taken the time to it.

**Comment by magol** [comment]
Ok, now I see that I can not blame the tools. I was simply careless when I recovered a bad commit, and did not restored it completely as it was before.

Now it works (hopefully)

I have at least learned a lot about GIT now, but I feel that I still do not really know what I'm doing. Normally I work with TFS at work, and with that it is not as easy to destroy for yourself.

**Comment by Liryna** [comment]
Thank you @magol for your contribution !
The git history of your branch is madness :cry: 
There is a mix of old commit and new and I was not able to recover it.
You probably had to make the changes in a new clean repository.

So I created a commit with all your changes https://github.com/dokan-dev/dokan-dotnet/commit/b07fa24a3796fadd656004c9c3669103c71e07ac

Doxygen documentation is now full ! Congratulation @magol ! :trophy:

**Comment by magol** [comment]
Sadly I'm not surprised at all.

I tried to use `git reset --soft HEAD~3` as you suggested. But I made more commits after that and ran `git reset --soft HEAD~3` again. And then a few more times after another few commit.
I saw that history was very strange, but I did not really know if it was suppose to be like that.

How should I do to get it right from the beginning?

Sorry I did it hard for you. I want normally to do everything as perfect as possible, but right now I'm inside of an area where I do not rely know what is right. Really frustrating. :-(

Thank you for your patience with me, and fixed so that my changes for me.
Really funny that the documentation is up :-)

**Comment by Liryna** [comment]
Here is some documentation: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
Also some git client that can help you doing it (like tortoisegit). You should look at the client you use and see if there is something for "rebase" your changes.

Git is a very powerfull tools but hard to master :smile: 

Yeap good to have finally a documentation :D !

**Pull request closed without merging**
